[project]
name = "fgdb-to-gpkg"
version = "0.1.0"
description = "A lightweight Python package that converts Esri File GeoDataBases into OGC GeoPackages"
authors = [
    {name = "Philip Orlando", email = "phlp.orlando@gmail.com"},
    ]

[project.dependencies]
fiona = "1.9.2"
geopandas = "0.12.2"