[project]
name = "fgdb-to-gpkg"
version = "0.1.0"
description = "A lightweight Python package that converts FileGeoDataBases into GeoPackages"
authors = [
    {name = "Philip Orlando", email = "phlp.orlando@gmail.com"},
    ]

[project.dependencies]
fiona
geopandas

[project.optional-dependencies]
test = [
  pytest
]
