# Source: https://jacobian.org/til/github-actions-poetry/
# Run this job on pushes to `main`, and for pull requests. If you don't specify
# `branches: [main], then this actions runs _twice_ on pull requests, which is
# annoying.

# Name of the workflow
name: Python Unit Tests with Poetry

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    # Use Docker container to avoid GDAL dependency issues
    container:
      image: osgeo/gdal:ubuntu-small-latest
      
    steps:
      - uses: actions/checkout@v2

      # Setup Python version specified
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install build-essential tools for compiling C extensions
      - name: Install build tools
        run: apt-get update && apt-get install -y build-essential

      # Cache the installation of Poetry
      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.6.1-0

      # Install Poetry using snok/install-poetry action
      - uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      # Cache your project dependencies
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      # Install dependencies with Poetry, avoiding caching of the project itself
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      # Install the project using Poetry to fully-exercise pyproject.toml
      - run: poetry install --no-interaction

      # Run tests with pytest as configured in pyproject.toml
      - run: poetry run pytest
